#!/bin/bash

# Function to display information about a subdomain
display_info() {
    local sub_domain=$1
    local domain=$2
    local record_type=$(dig +short -t $3 $sub_domain.$domain)
    local destination=$(dig +short $sub_domain.$domain)

    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Main script
if [ "$#" -eq 1 ]; then
    domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        display_info $sub $domain A
    done
elif [ "$#" -eq 2 ]; then
    domain=$1
    subdomain=$2
    display_info $subdomain $domain A
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

