#!/usr/bin/env bash
#configure nginx server to listen for port 80 again
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
sudo pkill -o nginx
