#!/usr/bin/env bash
# This script configures localhost and facebook.com resolution
# Copy hosts file to a new location
# Add localhost resolution
# Add facebook.com resolution
# Replace original hosts file with the modified one

cp /etc/hosts ~/hosts.new
sed -i '1s/^/127.0.0.2 localhost\n/' ~/hosts.new
sed -i '/localhost$/a 8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
